plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']

Metrics/AbcSize:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/BlockNesting:
  Max: 5

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 16

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/**/*'
