name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ '3.2', '3.3', '3.4' ]
    steps:
    - uses: actions/checkout@v5
    - name: Install BLAS and LAPACK
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev liblapacke-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake

  build-rocky:
    runs-on: ubuntu-latest
    name: Ruby 3.3 (Rocky)
    container: rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        run: |
          dnf update -y
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled crb
          dnf module -y enable ruby:3.3
          dnf install -y gcc make git libyaml-devel ruby-devel ruby openblas-devel
          bundle config silence_root_warning true
      - name: Build and test
        run: |
          bundle install
          bundle exec rake -- --with-opt-include="/usr/include/openblas"

  build-win:
    runs-on: windows-latest
    timeout-minutes: 10
    name: Ruby 3.4 (Windows)
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
      - name: Install OpenBLAS and LAPACK
        run: |
          pacman -Syu
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-openblas mingw-w64-ucrt-x86_64-lapack
      - name: Run the default task
        run: |
          bundle install
          bundle exec rake compile -- --with-opt-lib="C:\hostedtoolcache\windows\Ruby\3.4.7\x64\msys64\ucrt64\lib" --with-opt-include="C:\hostedtoolcache\windows\Ruby\3.4.7\x64\msys64\ucrt64\include\openblas"
          bundle exec rake test

  build-mac:
    runs-on: macos-latest
    name: Ruby 3.4 (macOS)
    steps:
    - uses: actions/checkout@v5
    - name: Install OpenBLAS
      run: |
        brew update
        brew install openblas
        brew info openblas
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake compile -- --with-opt-dir=/opt/homebrew/opt/openblas
        bundle exec rake test
